// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlb4ArhWd4mr4YKNv7oTEtKWCq9F7o-8s',
    appId: '1:554255169853:web:c349ee87552f846553ad54',
    messagingSenderId: '554255169853',
    projectId: 'simplenote-801b9',
    authDomain: 'simplenote-801b9.firebaseapp.com',
    storageBucket: 'simplenote-801b9.appspot.com',
    measurementId: 'G-DTXHD4LV45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhprmdbMm0jXDt6yrCa2XH33JD5LDDm-0',
    appId: '1:554255169853:android:b38f647255ccc50e53ad54',
    messagingSenderId: '554255169853',
    projectId: 'simplenote-801b9',
    storageBucket: 'simplenote-801b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQFRbbCn9vu0BwCR2CNzKgl20tSuHSyU',
    appId: '1:554255169853:ios:acfc45b95607a0ed53ad54',
    messagingSenderId: '554255169853',
    projectId: 'simplenote-801b9',
    storageBucket: 'simplenote-801b9.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQFRbbCn9vu0BwCR2CNzKgl20tSuHSyU',
    appId: '1:554255169853:ios:acfc45b95607a0ed53ad54',
    messagingSenderId: '554255169853',
    projectId: 'simplenote-801b9',
    storageBucket: 'simplenote-801b9.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlb4ArhWd4mr4YKNv7oTEtKWCq9F7o-8s',
    appId: '1:554255169853:web:5cbf3dee5bd6c43453ad54',
    messagingSenderId: '554255169853',
    projectId: 'simplenote-801b9',
    authDomain: 'simplenote-801b9.firebaseapp.com',
    storageBucket: 'simplenote-801b9.appspot.com',
    measurementId: 'G-Z4K21T7RSH',
  );
}
